language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: vndlovu
  password:
    secure: JLBI1D3F3zXBo6iRbZhs5xK51fRmgP6WLxM7DtLHuoBBin9F3aGFzhE47Tg5AUqgbjFuB5Vo89ZJN2CoaP+GqB2wmN99bgEZ6/QnZ2O/a2N5S13fWMAaPao9mu3SNVD4aGx6R8TmsQ6AX6FwzhlX9Opxxz1pxV7PCAdHYSThgWLWVzCQE5QPp1fs642bpMTg7/ouCyynhlV5WQN4nq4QVY0TlLkMEuskTUSSrvxbNqcECtmtW8jVzrpYo/MQjxr7JHxqoJDG3h4iMZBN6PYBS8n0TtLm132zoP7Cdz3sWlzGm7Ka1kwZzJ7FTUCsm+yIp72R6pr/DZlF6cczlj2ro9y31EwSAUorJQ2H4PyIk4Wwx7dNWskTaK/eh22Rrb5h6YZrm8qkXOKcYlOZwqqNHtcLQs37mkfljJfFolcnoAuOHFE1JlB8qHVYmUEowyHrjA4YDYbErJvl9luFXggSmXGggx3VUZ9l2oh4vYk+c10n6mdOJ/0VQjL/fvb/5PfrPWTyc6qAZiCsUx6bAmQoSOxNw219FQLm06Z4SC4S1t9jxHzW4mWFSZ469GZRCDLEoVrsgXn+bSn1ofjOzF2gDWgizhQdYDY67tlZELCLBW9eUvsGQ9S3B3+QoDkwXXrr0H7ZV9FKhIxFLtN3MPfJnqNA/2W17saciWh6+b5NQm4=
  on:
    tags: true
    repo: terrameijar/pycapital
    python: 3.6
